version: "3.9"
x-common-variables: &common-variables
services:
  nginx:
    build: ./nginx/ 
    container_name: nginx-container  
    ports:  
      - 8016:8016 
      - 8017:8017 #xdebug cp,,e 
    depends_on:
      - php
    volumes:
      - type: bind
        source: ./www/html/
        target: /var/www/html/  
  php:
    build: 
      context: .
      dockerfile: ./php/arm64.Dockerfile
    container_name: php-container  
    environment:
      - DB_HOST=db
      - DB_NAME=databasename
      - DB_USER=root
      - DB_PASS=HbR4oWyjQQWk
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./www/html/
        target: /var/www/html/ 
  db:
    image: mariadb:10.3
    volumes:
      - mysql-data:/var/lib/mysql
    environment:  
      MARIADB_ROOT_PASSWORD: "HbR4oWyjQQWk"
      MARIADB_DATABASE: "databasename"
      MARIADB_USER: "databaseuser"
      MARIADB_PASSWORD: "c5D574XFVEzj"
volumes:
  mysql-data: